from enum import Enum

class ChangeRequest_type(str, Enum):
    ADD_FOLDERS = "ADD_FOLDERS",
    SET_FOLDERS = "SET_FOLDERS",
    REMOVE_FOLDERS = "REMOVE_FOLDERS",
    REMOVE_FOLDERS_AND_BRANCH = "REMOVE_FOLDERS_AND_BRANCH",
    MAKE_ROOT = "MAKE_ROOT",
    SET_PARENT = "SET_PARENT",
    SET_TEXT = "SET_TEXT",
    SET_TEXTS = "SET_TEXTS",
    APPEND_TEXT = "APPEND_TEXT",
    SET_CONTENT = "SET_CONTENT",

